logging:
  config: classpath:logback-common.xml

spring:

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB

  thymeleaf:
    suffix: .html
    prefix: classpath:/templates

  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    enabled: true
    request-context-attribute: req
    settings:
      classic_compatible: true
      number_format: 0.##
    suffix: .html
    template-loader-path: classpath:/templates/

  datasource:
    druid:
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      aop-patterns: "com.jerry.up.lala..*.service.*,com.jerry.up.lala..*.mapper.*"
      useGlobalDataSourceStat: true
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        allow:
        url-pattern: /druid/*
        login-username: ${env.druid.username}
        login-password: ${env.druid.password}
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

    dynamic:
      primary: master
      lazy: true
      datasource:
        master:
          lazy: true
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${env.mysql.host}/lala_boot?autoReconnect=true&useAffectedRows=true&useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&allowMultiQueries=true
          username: ${env.mysql.username}
          password: ${env.mysql.password}

  redis:
    host: ${env.redis.host}
    password: ${env.redis.password}
    timeout: 300s
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1s
        min-idle: 0

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml

rocketmq:
  name-server: ${env.rocketmq.nameServer}
  producer:
    group: lala_${spring.application.name}_producer

sa-token:
  tokenName: Authorization
  timeout: -1
  activity-timeout: ${env.token.activityTimeout}
  is-concurrent: true
  is-share: false
  max-login-count: -1
  token-prefix: Bearer
  is-print: false
  is-log: false
  jwt-secret-key: ${env.token.jwtSecretKey}

  alone-redis:
    host: ${env.token.redis.host}
    port: ${env.token.redis.port}
    password: ${env.token.redis.password}
    database: ${env.token.redis.database}
    timeout: 60s
